# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20170802_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='report',
        ),
        migrations.AddField(
            model_name='report',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.Job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
