# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20170804_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportunit',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
