# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_reportunit_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
