# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('F', 'finished'), ('P', 'processing'), ('E', 'error')], default='P', max_length=64, null=True),
        ),
    ]
